### ISSUE TITLE
RuntimeError: Workflow did not execute cleanly.

### ISSUE THREAD

**Issue by costantinoai** [compneuro-ncu/fmridenoise#80] opened 2020-12-20 12:36 UTC
Hi,

after a few hours of preprocessing I got this error: 

> 201220-11:22:51,58 nipype.workflow INFO:
>          [MultiProc] Running 4 tasks, and 0 jobs ready. Free memory (GB): 39.55/40.35, Free processors: 15/19.
>                      Currently running:
>                        * fmridenoise_wf.ds_connectivity
>                        * fmridenoise_wf.ds_matrix_plot
>                        * fmridenoise_wf.ds_carpet_plot
>                        * fmridenoise_wf.ds_denoise
> 201220-11:22:51,138 nipype.workflow INFO:
>          [Node] Finished "fmridenoise_wf.ds_carpet_plot".
> 201220-11:22:51,490 nipype.workflow INFO:
>          [Node] Finished "fmridenoise_wf.ds_matrix_plot".
> 201220-11:22:51,532 nipype.workflow INFO:
>          [Node] Finished "fmridenoise_wf.ds_connectivity".
> 201220-11:22:53,56 nipype.workflow INFO:
>          [Job 1251] Completed (fmridenoise_wf.ds_carpet_plot).
> 201220-11:22:53,58 nipype.workflow INFO:
>          [Job 1252] Completed (fmridenoise_wf.ds_matrix_plot).
> 201220-11:22:53,60 nipype.workflow INFO:
>          [Job 1253] Completed (fmridenoise_wf.ds_connectivity).
> 201220-11:22:53,65 nipype.workflow INFO:
>          [MultiProc] Running 1 tasks, and 0 jobs ready. Free memory (GB): 40.15/40.35, Free processors: 18/19.
>                      Currently running:
>                        * fmridenoise_wf.ds_denoise
> 201220-11:24:21,442 nipype.workflow INFO:
>          [Node] Finished "fmridenoise_wf.ds_denoise".
> 201220-11:24:23,140 nipype.workflow INFO:
>          [Job 1243] Completed (fmridenoise_wf.ds_denoise).
> 201220-11:24:23,146 nipype.workflow INFO:
>          [MultiProc] Running 0 tasks, and 0 jobs ready. Free memory (GB): 40.35/40.35, Free processors: 19/19.
> 201220-11:24:25,138 nipype.workflow INFO:
>          ***********************************
> 201220-11:24:25,139 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Smoother.a15.a0.a0
> 201220-11:24:25,139 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-080922-root-Smoother.a15.a0.a0-a1e477db-d770-468b-a3f7-bae60afbd0fe.pklz
> 201220-11:24:25,139 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Smoother.a07.a0.a0
> 201220-11:24:25,139 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-081221-root-Smoother.a07.a0.a0-183df32c-4612-4cfb-8ed2-78dac06de7cf.pklz
> 201220-11:24:25,139 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a03.a0.a6.a0
> 201220-11:24:25,139 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-084619-root-Denoiser.a03.a0.a6.a0-8adaf19d-a7e6-41db-b4a3-80d38a510e3f.pklz
> 201220-11:24:25,139 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a03.a0.a5.a0
> 201220-11:24:25,139 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-091445-root-Denoiser.a03.a0.a5.a0-877eb3c9-894d-44b6-94f3-25ba2a0d5c9b.pklz
> 201220-11:24:25,139 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a03.a0.a4.a0
> 201220-11:24:25,139 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-095315-root-Denoiser.a03.a0.a4.a0-9e3e769a-f5f1-4c9e-b575-be343e36ee75.pklz
> 201220-11:24:25,139 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a03.a0.a3.a0
> 201220-11:24:25,139 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103322-root-Denoiser.a03.a0.a3.a0-69228567-8ad0-431a-b747-a72575a866f8.pklz
> 201220-11:24:25,139 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a23.a0.a2.a0
> 201220-11:24:25,139 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103854-root-Denoiser.a23.a0.a2.a0-bf0e1b13-117c-48fa-8e6a-c53cb312e0f6.pklz
> 201220-11:24:25,140 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a22.a0.a2.a0
> 201220-11:24:25,140 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103904-root-Denoiser.a22.a0.a2.a0-fe036326-7726-4f50-b49b-274b5384cf22.pklz
> 201220-11:24:25,140 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a21.a0.a2.a0
> 201220-11:24:25,140 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103914-root-Denoiser.a21.a0.a2.a0-0010cd9e-0b84-4b4d-aa0b-d8b2b290f69d.pklz
> 201220-11:24:25,140 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a20.a0.a2.a0
> 201220-11:24:25,140 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103916-root-Denoiser.a20.a0.a2.a0-f547dae1-2351-49e2-bad7-b1823ac4ff18.pklz
> 201220-11:24:25,140 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a19.a0.a2.a0
> 201220-11:24:25,140 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103918-root-Denoiser.a19.a0.a2.a0-d8f09f5c-8db1-42f5-b240-5064259680d0.pklz
> 201220-11:24:25,140 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a18.a0.a2.a0
> 201220-11:24:25,140 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103920-root-Denoiser.a18.a0.a2.a0-67d1e1a1-0d22-4789-8903-c23983f3c93e.pklz
> 201220-11:24:25,140 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a17.a0.a2.a0
> 201220-11:24:25,140 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103922-root-Denoiser.a17.a0.a2.a0-c4e98aca-0cef-40da-aaaa-78a4ca9f28c1.pklz
> 201220-11:24:25,140 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a16.a0.a2.a0
> 201220-11:24:25,141 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103924-root-Denoiser.a16.a0.a2.a0-be880ae2-2242-44ef-a60c-b3d7634c921c.pklz
> 201220-11:24:25,141 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a14.a0.a2.a0
> 201220-11:24:25,141 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103926-root-Denoiser.a14.a0.a2.a0-90c7a15f-dce3-48d3-9de2-659b6f52f9c4.pklz
> 201220-11:24:25,141 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a13.a0.a2.a0
> 201220-11:24:25,141 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103928-root-Denoiser.a13.a0.a2.a0-b0992586-9981-4d53-afb0-da4dbb95c053.pklz
> 201220-11:24:25,141 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a12.a0.a2.a0
> 201220-11:24:25,141 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103930-root-Denoiser.a12.a0.a2.a0-53343747-395d-488d-bea3-27043a60398e.pklz
> 201220-11:24:25,141 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a11.a0.a2.a0
> 201220-11:24:25,141 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103932-root-Denoiser.a11.a0.a2.a0-9a9e4030-fc74-4900-bc6e-098e91d77f70.pklz
> 201220-11:24:25,141 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a10.a0.a2.a0
> 201220-11:24:25,141 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103934-root-Denoiser.a10.a0.a2.a0-ec3d1ea1-7f91-42c2-8d2e-e01e78469dd7.pklz
> 201220-11:24:25,141 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a09.a0.a2.a0
> 201220-11:24:25,141 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103936-root-Denoiser.a09.a0.a2.a0-2ac7d9bd-efd4-4020-b0be-9021e99c2bee.pklz
> 201220-11:24:25,141 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a08.a0.a2.a0
> 201220-11:24:25,141 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103938-root-Denoiser.a08.a0.a2.a0-58358f45-da14-4eab-9a90-8bbc627da5f6.pklz
> 201220-11:24:25,142 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a06.a0.a2.a0
> 201220-11:24:25,142 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103940-root-Denoiser.a06.a0.a2.a0-61ef3f85-4a84-429e-a8a3-7d0cd725b675.pklz
> 201220-11:24:25,142 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a05.a0.a2.a0
> 201220-11:24:25,142 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103942-root-Denoiser.a05.a0.a2.a0-764c9073-4369-43fb-af41-75fb9aca5fd9.pklz
> 201220-11:24:25,142 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a04.a0.a2.a0
> 201220-11:24:25,142 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103944-root-Denoiser.a04.a0.a2.a0-6a572402-47b4-4a9b-a923-ca918fafdb09.pklz
> 201220-11:24:25,142 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a03.a0.a2.a0
> 201220-11:24:25,142 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103946-root-Denoiser.a03.a0.a2.a0-f72a34d5-56b3-4fcb-9e14-dfa49747573a.pklz
> 201220-11:24:25,142 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a02.a0.a2.a0
> 201220-11:24:25,142 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103948-root-Denoiser.a02.a0.a2.a0-8547e524-e938-4abc-b686-afc34b639c67.pklz
> 201220-11:24:25,142 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a01.a0.a2.a0
> 201220-11:24:25,142 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103950-root-Denoiser.a01.a0.a2.a0-e939d746-2a8c-4c3e-a32a-58686af6e412.pklz
> 201220-11:24:25,142 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a00.a0.a2.a0
> 201220-11:24:25,142 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-103952-root-Denoiser.a00.a0.a2.a0-ad5c6250-978d-424d-8210-a044517dd2e8.pklz
> 201220-11:24:25,143 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a03.a0.a1.a0
> 201220-11:24:25,143 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111328-root-Denoiser.a03.a0.a1.a0-05cef7e7-c757-40f9-b182-7a525e724fd0.pklz
> 201220-11:24:25,143 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a23.a0.a0.a0
> 201220-11:24:25,143 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111906-root-Denoiser.a23.a0.a0.a0-75bf8dc5-c045-4d97-a8de-7557046879a8.pklz
> 201220-11:24:25,143 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a22.a0.a0.a0
> 201220-11:24:25,143 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111912-root-Denoiser.a22.a0.a0.a0-1d5b8a91-3b39-40f6-b2bd-8f2c1f9b1a91.pklz
> 201220-11:24:25,143 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a21.a0.a0.a0
> 201220-11:24:25,143 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111921-root-Denoiser.a21.a0.a0.a0-4dd8824b-ff24-4ec9-82fc-2fcca5063c5f.pklz
> 201220-11:24:25,143 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a20.a0.a0.a0
> 201220-11:24:25,143 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111926-root-Denoiser.a20.a0.a0.a0-0c83da87-12ad-4c87-8e1d-1666711e7374.pklz
> 201220-11:24:25,143 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a19.a0.a0.a0
> 201220-11:24:25,143 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111928-root-Denoiser.a19.a0.a0.a0-563dfa37-cdfd-4f4a-bd77-bb524ad68873.pklz
> 201220-11:24:25,143 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a18.a0.a0.a0
> 201220-11:24:25,143 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111930-root-Denoiser.a18.a0.a0.a0-6825df5a-99d5-4b38-9c56-4279debd91e2.pklz
> 201220-11:24:25,144 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a17.a0.a0.a0
> 201220-11:24:25,144 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111932-root-Denoiser.a17.a0.a0.a0-9d315b1f-fb9b-4564-bcac-ca82011bee04.pklz
> 201220-11:24:25,144 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a16.a0.a0.a0
> 201220-11:24:25,144 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111934-root-Denoiser.a16.a0.a0.a0-f8d5a948-e67c-41b5-bdd5-45eb7da5a3ac.pklz
> 201220-11:24:25,144 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a14.a0.a0.a0
> 201220-11:24:25,144 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111936-root-Denoiser.a14.a0.a0.a0-c19f1b6f-2a9e-4b31-bab2-ccae7bec5a16.pklz
> 201220-11:24:25,144 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a13.a0.a0.a0
> 201220-11:24:25,144 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111938-root-Denoiser.a13.a0.a0.a0-71d76468-de1b-40d1-8bfd-d50b678b6f11.pklz
> 201220-11:24:25,144 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a12.a0.a0.a0
> 201220-11:24:25,144 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111940-root-Denoiser.a12.a0.a0.a0-cc3969b5-8ea2-4f5e-b94f-f3ad4ccd849c.pklz
> 201220-11:24:25,144 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a11.a0.a0.a0
> 201220-11:24:25,144 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111942-root-Denoiser.a11.a0.a0.a0-b0fdba20-2fc9-49a9-9caa-bbcb46bb33aa.pklz
> 201220-11:24:25,144 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a10.a0.a0.a0
> 201220-11:24:25,144 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111944-root-Denoiser.a10.a0.a0.a0-9521e5f2-90ef-4b13-b114-ad4329435676.pklz
> 201220-11:24:25,145 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a09.a0.a0.a0
> 201220-11:24:25,145 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111946-root-Denoiser.a09.a0.a0.a0-bc05e039-f39c-4802-b4f1-1dd4d28fc9b0.pklz
> 201220-11:24:25,145 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a08.a0.a0.a0
> 201220-11:24:25,145 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111948-root-Denoiser.a08.a0.a0.a0-12d3c1fb-80f4-447d-b6ed-928e179cc0be.pklz
> 201220-11:24:25,145 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a06.a0.a0.a0
> 201220-11:24:25,145 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111950-root-Denoiser.a06.a0.a0.a0-ad4facd6-7fbc-4fd2-b67b-19d6de337cd9.pklz
> 201220-11:24:25,145 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a05.a0.a0.a0
> 201220-11:24:25,145 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111952-root-Denoiser.a05.a0.a0.a0-69d42fec-bbc3-4080-a82d-caaa5ed939d0.pklz
> 201220-11:24:25,145 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a04.a0.a0.a0
> 201220-11:24:25,145 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111954-root-Denoiser.a04.a0.a0.a0-c08aa2ec-feb8-41b6-9873-7281fa3cd370.pklz
> 201220-11:24:25,145 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a03.a0.a0.a0
> 201220-11:24:25,145 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111956-root-Denoiser.a03.a0.a0.a0-7a9948c9-43e5-43e7-a7c3-7842ae49f389.pklz
> 201220-11:24:25,145 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a02.a0.a0.a0
> 201220-11:24:25,145 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-111958-root-Denoiser.a02.a0.a0.a0-6f7cfd71-65d5-43d6-85c5-e1b6940939f7.pklz
> 201220-11:24:25,145 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a01.a0.a0.a0
> 201220-11:24:25,146 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-112000-root-Denoiser.a01.a0.a0.a0-2952d3e2-fa00-423e-9912-96e6faadc7c4.pklz
> 201220-11:24:25,146 nipype.workflow ERROR:
>          could not run node: fmridenoise_wf.Denoiser.a00.a0.a0.a0
> 201220-11:24:25,146 nipype.workflow INFO:
>          crashfile: /fmridenoise-src/crash-20201220-112002-root-Denoiser.a00.a0.a0.a0-dce67b92-ccf3-4224-a8ef-10b18e522855.pklz
> 201220-11:24:25,146 nipype.workflow INFO:
>          ***********************************
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/fmridenoise-src/fmridenoise/__main__.py", line 236, in <module>
>     main()
>   File "/fmridenoise-src/fmridenoise/__main__.py", line 228, in main
>     compare(args)
>   File "/fmridenoise-src/fmridenoise/__main__.py", line 203, in compare
>     workflow.run(plugin="MultiProc", plugin_args=workflow_args)
>   File "/usr/local/lib/python3.8/dist-packages/nipype-1.6.0-py3.8.egg/nipype/pipeline/engine/workflows.py", line 632, in run
>     runner.run(execgraph, updatehash=updatehash, config=self.config)
>   File "/usr/local/lib/python3.8/dist-packages/nipype-1.6.0-py3.8.egg/nipype/pipeline/plugins/base.py", line 192, in run
>     report_nodes_not_run(notrun)
>   File "/usr/local/lib/python3.8/dist-packages/nipype-1.6.0-py3.8.egg/nipype/pipeline/plugins/tools.py", line 97, in report_nodes_not_run
>     raise RuntimeError(
> RuntimeError: Workflow did not execute cleanly. Check log for details

any idea? the errors seem to go back to quality_measures.py, line 191 

> [Node] Running "QualityMeasures" ("fmridenoise.interfaces.quality_measures.QualityMeasures")
> 201220-14:01:44,328 nipype.workflow WARNING:
>          Storing result file without outputs
> 201220-14:01:44,635 nipype.workflow WARNING:
>          [Node] Error on "fmridenoise_wf.QualityMeasures" (/workdir/fmridenoise_wf/_run_1/_task_loc/_pipeline_path_..fmridenoise-src..fmridenoise..pipelines..pipeline-Null.json/QualityMeasures)
> 201220-14:01:44,983 nipype.workflow INFO:
>          [Node] Finished "fmridenoise_wf.ds_group_connectivity".
> 201220-14:01:45,309 nipype.workflow INFO:
>          [Job 11] Completed (fmridenoise_wf.ds_group_connectivity).
> 201220-14:01:45,313 nipype.workflow ERROR:
>          Node QualityMeasures.a0.a4.a0 failed to run on host e88c2dd8612b.
> 201220-14:01:45,313 nipype.workflow ERROR:
>          Saving crash info to /fmridenoise-src/crash-20201220-140145-root-QualityMeasures.a0.a4.a0-12752d5d-2236-467f-8193-be760003cd82.pklz
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/nipype-1.6.0-py3.8.egg/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/usr/local/lib/python3.8/dist-packages/nipype-1.6.0-py3.8.egg/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/usr/local/lib/python3.8/dist-packages/nipype-1.6.0-py3.8.egg/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/usr/local/lib/python3.8/dist-packages/nipype-1.6.0-py3.8.egg/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/usr/local/lib/python3.8/dist-packages/nipype-1.6.0-py3.8.egg/nipype/interfaces/base/core.py", line 434, in run
>     runtime = self._run_interface(runtime)
>   File "/fmridenoise-src/fmridenoise/interfaces/quality_measures.py", line 284, in _run_interface
>     self._calculate_quality_measures(
>   File "/fmridenoise-src/fmridenoise/interfaces/quality_measures.py", line 255, in _calculate_quality_measures
>     summary, edges_weight, fc_fd_corr_vector, excluded_subjects = self._quality_measure(
>   File "/fmridenoise-src/fmridenoise/interfaces/quality_measures.py", line 230, in _quality_measure
>     fc_fd_corr, fc_fd_pval = cls.calculate_fc_fd_correlations(group_conf_subsummary, group_corr_subvec)
>   File "/fmridenoise-src/fmridenoise/interfaces/quality_measures.py", line 191, in calculate_fc_fd_correlations
>     corr = pearsonr(x=fc, y=fd)
>   File "/usr/local/lib/python3.8/dist-packages/scipy-1.5.0-py3.8-linux-x86_64.egg/scipy/stats/stats.py", line 3838, in pearsonr
>     raise ValueError('x and y must have length at least 2.')
> ValueError: x and y must have length at least 2.

the denoised files are there, I attached the snapshot of a volume - can you please let me know if this is the expected output? 

![Capture](https://user-images.githubusercontent.com/59078281/102713483-ac12f180-431c-11eb-9b5f-5bb55e53c43e.PNG)

Also, no report was generated.

last thing: can fmridenoiser restart from an error if the working folder remains untouched, or do I need to restart?

**Comment by SiegfriedWagner** [comment] 2020-12-20 14:58
Can be restarted and work will be resumed, sometimes fmridenoise crashes
because system runs out of memeory. I will look at it later.

**Comment by costantinoai** [comment] 2020-12-20 15:18
It run successfully now with 2 subjects and the no aroma pipelines flag. Perhaps it run out of memory or it didn’t like having only one participant.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SiegfriedWagner** [comment] 2020-12-20 19:46
The image issue - i have no idea why the images looks so distorted.
@kfinc @kbonna we should consider more testing for images files, maybe even as part of automatic tests.

Bug in quality measures I should be able to isolate and resolve,
You have wait until after 28 December because I have no access to my development PC during winter holiday.

**Comment by costantinoai** [comment] 2020-12-21 01:18
so I suppose the images shouldn't look like this? in the working folder, the smoothed images make sense - there is no distortion other than the smoothing. So perhaps the problem is in the denoising itself?

**Comment by SiegfriedWagner** [comment] 2020-12-21 08:54
Denosing is performed with nilearn function. We just made wraper for it as
an iterface. Either there is problem with input params or confounds on our
side or there is some nasty bug in nilearn. (I suppose it's case with our
code)

**Comment by costantinoai** [comment] 2020-12-26 08:40
So, the `ValueError: x and y must have length at least 2.` is raised because in quality_metrics.py, line 191 

`corr = pearsonr(x=fc, y=fd)`

expects more than 1 value (obviously). The error is not raised if more than one participant is processed, so it might be useful to have this in the docs or update the code accordingly.

I still didn't figure out why the distorsion in the images - I guess I'll have to wait for you guys to look into it!

Thanks

**Comment by SiegfriedWagner** [comment] 2020-12-28 12:07
> ![Capture](https://user-images.githubusercontent.com/59078281/102713483-ac12f180-431c-11eb-9b5f-5bb55e53c43e.PNG)

I ran fmridenoise on exactly [this](https://openneuro.org/datasets/ds003059/versions/1.0.0) data (after fmriprep preprocesing) and the results looks kinda normal. I mean images look like brains activation and not some random noise. It's hard for me to replicate your invalid output and/or confirm if there is a problem on our side.

**Comment by costantinoai** [comment] 2020-12-28 12:13
can you please post an image of the desired output? 

I am not sure then what is going on. the fmridenoise I am using is the dev branch, built on docker. I tried to run it again on ther subjects, but I still have the same sort of output image. Is there any file I can upload to make sure the denoising parameters/confounds look fine?

Also, is there a way to avoid the smoothing on the data? (I will run an MVPA on the denoised data, so it would probably better to avoid smoothing)

**Comment by SiegfriedWagner** [comment] 2020-12-28 12:38
Smoothing is mandatory but I can add it as optional step soon.

![Screenshot from 2020-12-28 13-09-27](https://user-images.githubusercontent.com/28673155/103214756-9d769c80-4911-11eb-8152-f10c5fd3b66a.png)
![Screenshot from 2020-12-28 13-36-14](https://user-images.githubusercontent.com/28673155/103214783-b1ba9980-4911-11eb-82f5-18116d1a9e8d.png)
The first is from pipeline Null and the second is from actual denoising.

**Comment by costantinoai** [comment] 2020-12-29 02:33
What can I do the debug this problem? what are the input files to generate the denoised images?

I run it again and this is the result (overlaid over the functional nifti)

![sub-02_task-exp_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold@0 3x](https://user-images.githubusercontent.com/59078281/103254687-6d470080-49da-11eb-8a6b-20256da6ca46.png)

**Comment by costantinoai** [comment] 2021-01-03 04:20
Are you guys looking into this, or should I close the issue and look for another tool?

**Comment by SiegfriedWagner** [comment] 2021-01-04 06:52
Sorry late response - I had winter break.
Personally I am unable to provide more support on my own for this issue, I am unable to reproduce it using mentioned dataset (and few other from our lab). 
You can look at files left in workdir (you can set workdir with flag `-w`) - it contains output files from every step of analysis.
If you want provide more insight into this problem I would be glad, otherwise we can close the issue - decision is up to you.

**Comment by costantinoai** [comment] 2021-01-04 09:23
If you tell me what information do you need I might be able to provide. I already told you that the smoothed images look fine because I had a look into the working folder before. I just don’t know what kind of information you need to try to understand where the problem lies. For example, what are the files read by fmridenoise to determine how to perform the denoise? Obviously there is some problem with the brain mask also, so if you can point me in the right direction I may be able to provide you the files (or check them by myself) needed to solve the issue - or at least understand if and where my data is problematic.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Closed** 2021-01-16 15:05 UTC
Labels: bug, invalid

**Comment by manzouri** [comment] 2021-03-02 11:22
Hello, Is there any update regarding this issue? I have the same problem !
